import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import { CartProvider } from "@/lib/cart-context";
import { WishlistProvider } from "@/lib/wishlist-context";
import { CheckoutProvider } from "@/lib/checkout-context";
import PageTracker from '@/components/analytics/PageTracker';
import { Suspense } from 'react';
import CartSidebar from "@/components/ui/cart-sidebar";

export const metadata: Metadata = {
  title: "Low Religion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CartProvider>
          <WishlistProvider>
            <CheckoutProvider>
              <a href="#main-content" className="skip-to-content">
                Skip to main content
              </a>
              <ErrorReporter />
              <div id="main-content">
                <Suspense fallback={null}>
                  <PageTracker />
                </Suspense>
                {children}
              </div>
              <CartSidebar />
              <VisualEditsMessenger />
            </CheckoutProvider>
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
